version: "3.7"

services:

  plex:
    image: linuxserver/plex:latest
    expose:
      - 32400
      - 33400
    ports:
     - 32400:32400
     - 33400:33400
    environment:
      - TZ=Europe/Madrid
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
    volumes:
      - /Users/vicenteruiz/docker/plex:/config
      - ${MEDIA}:/media
      - /Users/vicenteruiz/docker/plex/transcode:/transcode
    restart: unless-stopped

  transmission:
    image : jaymoulin/transmission:3.00-1.6.1
    command: transmission-daemon -f -g /config
    volumes:
      - ./transmission:/config
      - ${STORAGE}/torrents:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    expose:
      - 9091
    restart: unless-stopped

  flexget:
    image: wiserain/flexget:3.5
    volumes:
      - ./flexget:/config
      - ./flexget/custom-cont-init.d:/custom-cont-init.d
      - ${STORAGE}/torrents:/downloads
      - ${MEDIA}:/storage
    ports:
      - 5050:5050
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TORRENT_PLUGIN=transmission
      - FG_WEBUI_PASSWD=fl3xg3tp4ss # la puedes cambiar por la que quieras
    restart: unless-stopped