services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: bridge
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
      - PLEX_CLAIM=claim-4vJUAFVyDR1NR_4Xz2gd
    volumes:
      - ${STORAGE}/Plex Config:/config
      - ${MEDIA}:/media
    ports:
      - 32400:32400
    restart: unless-stopped

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./deluge:/config
      - ${STORAGE}/torrents:/downloads
    ports:
      - 8112:8112
      - 6881:6881
      - 58846:58846
      - 6881:6881/udp
    restart: unless-stopped

  flexget:
    image: wiserain/flexget:3.5
    container_name: flexget
    environment:
      - PUID=1001
      - PGID=1001
      - FG_WEBUI_PASSWD=${PW}
      - TZ=${TZ}
    volumes:
      - ./flexget:/config
      - ./flexget/custom-cont-init.d:/custom-cont-init.d
      - ${STORAGE}/torrents:/downloads
      - ${MEDIA}:/storage
    ports:
      - 5050:5050
    restart: unless-stopped
