version: "3.7"

services:
  plex:
    container_name: plex
    image: linuxserver/plex
    ports:
      - 32400:32400
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
    volumes:
      - ${STORAGE}/plex:/config
      - ${MEDIA}:/media
      - ${STORAGE}/plex/transcode:/transcode
  

  transmission:
    image : jaymoulin/transmission:3.00-1.6.1
    command: transmission-daemon -f -g /config
    volumes:
      - ./transmission:/config
      - ${STORAGE}/torrents:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    expose:
      - 9091
    restart: unless-stopped

  flexget:
    image: wiserain/flexget:3.5
    volumes:
      - ./flexget:/config
      - ./flexget/custom-cont-init.d:/custom-cont-init.d
      - ${STORAGE}/torrents:/downloads
      - ${MEDIA}:/storage
    ports:
      - 5050:5050
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TORRENT_PLUGIN=transmission
      - FG_WEBUI_PASSWD=fl3xg3tp4ssB41l3n
    restart: unless-stopped